### ISSUE TITLE
Go101: Improvements/idomatic go

### ISSUE THREAD

**Issue by kcalvinalvin** [chloe-codes1/TIL#3]
> $ export PATH=$PATH:/usr/local/go/bin

You usually want to setup your $GOPATH variable. Go has 2 path environment variables which are ```GOPATH``` and ```GOROOT```. ```GOROOT```. ```GOROOT``` is where your ```go``` binaries are and if you do ```sudo apt install golang-1.14-go```, it should install ```go``` to the default path and you don't have to worry about it.

```GOPATH``` is your user go environment path and this should be set to where your project files are. When you import any packages with ```go import``` the binary will fetch them in your ```GOPATH```. Idomatic go has the GOPATH at ```$HOME/go```. This is important for when you do ```go install``` or ```go import``` as go will look for the ```GOPATH``` variable. So ```export GOPATH=$HOME/go``` and ```export PATH=$PATH:$GOPATH/bin``` is important to setup.

Also I would point out that Go has a good build system.

1. It insanely fast build times and is one of the reasons I favor Go over any other languages. Even with projects that are thousands of lines long, go will compile in a matter of seconds. 

2. Code imports are based of off url imports. This is very helpful with managing dependencies. Go Modules let you hash the url at the time of import like lock files in other build systems.

3. No import cycles. Just makes it easier to manage different packages.

Some useful resources with go are: gobyexample.com, tour.golang.org, blog.golang.org, dave.cheney.net
A must read is: https://golang.org/doc/effective_go.html

Welcome to Go! Do ask questions if you have any :)

**Comment by chloe-codes1** [comment]
Thank you SO MUCH for this!
I set the **Go environment variables** on my laptop just like you recommended (and it worked well) and updated the `01_Go_basics.md`.
Thank you Calvin! You are the best!
